### ISSUE TITLE
HTTP ERROR 500 after updating from r1070 to r1295 per upgrade instructions

### ISSUE THREAD

**Issue by mikelatta** [projectsend/projectsend#1031]
After upgrading from r1070 to r1295 I now have HTTP ERROR 500.

Previous version was working fine but took the suggestion in the admin panel to update to r1295 version.

Here are some of the server components installed at my shared hosting platform:

cPanel Version 94.0 (build 18)
Apache Version 2.4.51
PHP Version 7.4.25
MySQL Version 10.3.31-MariaDB-cll-lve

The following php extensions enabled:
pdo enabled for mysql
pdo_mysql version 10.3.31
mbstring version 1.3.2
gettext enabled
fileinfo version 537
gd version 2.2.5
xml version 2.9.7

I have followed the instructions from [https://www.projectsend.org/how-to-update-projectsend/](url) using a Windows host and using FileZilla FTP client to perform the update to our shared hosting provider.

No error messages are being made that I can see except for the HTTP ERROR 500 as this is a shared hosting platform.

I have currently replace the #1029  php file per #1017 with no change and still receiving HTTP ERROR 500.

Our site is now currently down and I'm looking for any assistance to get it back up and running.

Any suggestions anyone may have I willing to give it a try.

First time posting to GitHub so If you need any additional information to solve my issues, just let me know.

**Comment by mikelatta** [comment]
I have added some of the latest revisions that were done a couple of months ago as I do not know when the cutoff date was for r1295 and still HTTP ERROR 500.

I did check footer.php and it did respond with a blank page and no error. 

From the source code I got:
`</div> <!-- container-fluid -->`

I'm still doing some troubleshooting myself and awaiting any suggestions.

**Comment by ignacionelson** [comment]
@mikelatta Hi Mike!
Please check with this beta version and let me know if it fixes the issue for you
https://www.projectsend.org/download/409/

**Comment by mikelatta** [comment]
any instructions to do with the beta version?

I'm overwriting the files on our site right now using the same FTP process.

**Comment by mikelatta** [comment]
Logged in as system admin into Project Send and testing everything.

System Notice: The database was updated to support this version of the software.

So far so good will update after testing.

**Comment by mikelatta** [comment]
Everything seems to be working but the preview function for pdf files. The system noticed that it should not offer a preview for a zip file but it did for pdf file and when we click the preview button it pops out a window and it shows the name but under the name it shows a black box where I would guess would be a preview of the pdf.

Update:

I have been able to find out that the URL that the preview is using for the pdf files is getting a HTTP ERROR 500.

I think it may have something to do with the .htaccess file in the uploads folder (a guess at this point)

Let me know what I should be fixing to get it to work with pdf files and can the preview function be disabled if we would like to?

**Comment by mikelatta** [comment]
Any suggestions @ignacionelson?

**Comment by ignacionelson** [comment]
Sorry. I haven't been able to dig into this yet, I'll try to run a few tests this week

**Comment by mikelatta** [comment]
@ignacionelson Any updates and suggestions?

**Comment by ignacionelson** [comment]
There have been a few issues regarding pdf files so I'm looking into implementing pdf.js which I believe will help solve most of them. Some are really weird and I cannot seems to reproduce them. But by the changes this will bring I believe it will be solved.
In your case, have you renamed the .htaccess files to see if the preview worked again?

**Comment by mikelatta** [comment]
@ignacionelson I have fixed (you will have to let me know) my PDF issues by modifying the .htaccess file. The code in the .htaccess file that was preventing the PDF files from preview and not download was:

```
<FilesMatch "\.(html|htm|asp|js|ico|swp)$">
    Order Deny,Allow
    Deny from all
</Files>

```
I have replaced and customized the .htaccess file to be:

```
Options -Indexes

SetEnvIf Request_URI "(^|/)[-\w]+\.(pdf|zip|doc|docx|txt|rtf|ppt|pptx|xls|mp4)$" allowed

<Files index.php>
    Order Allow,Deny
    Allow from all
</Files>

<Files *>
   Order deny,allow
   Deny from all
   Allow from env=allowed
</Files>
```
This is currently working for me on version r1330 for PDF and ZIP files. I have added additional extensions for future use.

I look forward to your comments.

**Comment by AdimoUK** [comment]
Apologies for digging this thread up from the dead but it's the first result in Google when searching for the problem (ProjectSend error 500 file preview) and since the issue is still marked as open...

I've noticed in the .htaccess file in /upload/files/ path, the rule that is breaking and causing error 500 for me is:

```
<FilesMatch "\.(html|htm|asp|js|ico|swp)$">
    Order Deny,Allow
    Deny from all
</Files>
```

This is flagged as incorrectly closed in the server logs: 
```
[core:alert] [/var/www/vhosts/***.com/upload/files/.htaccess](<redacted paths for privacy>): Expected </FilesMatch> but saw </Files>
```

To fix this issue, all I had to do is terminate the rule correctly, so:

```
<FilesMatch "\.(html|htm|asp|js|ico|swp)$">
    Order Deny,Allow
    Deny from all
</FilesMatch>
```

This has fixed error 500 for me. This seems to have been now fixed in commit 65e1cba028718535990e3328b4a5494ee12c7937 - unsure how I still have had this old .htaccess file but I'm posting this in case anyone else also has this problem.

**Comment by ignacionelson** [comment]
This issue is being closed as part of a bulk cleanup. ProjectSend has undergone significant changes since this was reported (including r1720 and r1994), and many older issues no longer apply to the current codebase.

If you are still experiencing this problem on the latest version, please open a new issue with updated details and we'll be happy to look into it. Thank you for your contribution!
