### ISSUE TITLE
No email notification to sysadmin 

### ISSUE THREAD

**Issue by iincitr** [projectsend/projectsend#881]
For a new user want to register to the system there is not any notification email to sysadmin or account that waiting to approve.

This may be added to handle newcomer.

**Comment by MrApe** [comment]
This actually seems like a bug. I also have this. After self-registration an empty page (only header) is shown. If debug is enabled (`define('DEBUG', true);` in e.g. `app.php`) an error is shown:

```
Fatal error: Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'requested_by' cannot be null in /var/www/html/includes/Classes/MembersActions.php:326 
Stack trace: 
#0 /var/www/html/includes/Classes/MembersActions.php(326): PDOStatement->execute() 
#1 /var/www/html/includes/Classes/Users.php(500): ProjectSend\Classes\MembersActions->group_request_membership() 
#2 /var/www/html/register.php(51): ProjectSend\Classes\Users->triggerAfterSelfRegister() 
#3 {main} thrown in /var/www/html/includes/Classes/MembersActions.php on line 326
```

**Comment by serg499** [comment]
I also have similar issue: After self-registration an empty page (only header) is shown.
When I try to debug (thanks to **MrApe**), I get the following error:
`Fatal error: Uncaught Error: Undefined constant "ProjectSend\Classes\CURRENT_USER_LEVEL" in /mysite/includes/Classes/Users.php:842 
Stack trace: #0 /mysite/includes/Classes/Users.php(464): ProjectSend\Classes\Users->limitUploadToSave() 
#1 /mysite/register.php(45): ProjectSend\Classes\Users->create() 
#2 {main} thrown in /mysite/includes/Classes/Users.php on line 842`

**Comment by ehawman** [comment]
Is this similar to my poorly titled #1208?

**Comment by serg499** [comment]
> Is this similar to my poorly titled #1208?

Not exactly as I don't use Google for the authentication. The issue that I have is for built-in user registration process.

**Comment by serg499** [comment]
Actually it's a pretty big and important bug. A lot of users can be affected. How can we fix that?

**Comment by ignacionelson** [comment]
As a temp fix, what happens if you set the option to CC all emails and add your address there?

**Comment by serg499** [comment]
I was meaning: After self-registration an empty page (only header) is shown.
Looks like the bug is similar, but I probably should create a separate thread for new registration empty page bug.

**Comment by ehawman** [comment]
@ignacionelson I attempted this. Still unable to generate any emails from registering a new client.

**Comment by ignacionelson** [comment]
Is this the only email thats not going out to admins?

**Comment by ehawman** [comment]
As far as I'm aware. "New files uploaded by clients" goes out just fine, and once I checked the box to also send to the "from" account, I started seeing "New files uploaded for you" cc's.

**Comment by ignacionelson** [comment]
I think the issue is very clear now, sorry I didn't get it before. I'll try to post a fix as soon as it's done

**Comment by ignacionelson** [comment]
@serg499 Your error should be fixed here f2797d4
I'll check the other one

**Comment by serg499** [comment]
@ignacionelson Thank you, Ignacio! Unfortunately, it hasn't fixed this thing. Probably, there's another error that prevents the showing of the last registration step. Chrome console shows error 500 in the register.php. Tomorrow I'll try to debug better to help you to locate the issue. Again, thank you for help!

**Comment by serg499** [comment]
Still have this bug. New clients are able to create a new account, but they don't see any confirmation about that. Just a white screen with our logo...

define('DEBUG', true) gives the following:
`Fatal error: Uncaught Error: Undefined constant "ProjectSend\Classes\CURRENT_USER_LEVEL" in .../includes/Classes/Users.php:840 Stack trace: #0 .../includes/Classes/Users.php(463): ProjectSend\Classes\Users->limitUploadToSave() #1 .../register.php(44): ProjectSend\Classes\Users->create() #2 {main} thrown in .../includes/Classes/Users.php on line 840`

**Comment by SenorFernando** [comment]
I Had the same bug, turns out that after a lot of playing around I noticed the notification gets sent to my notification mailbox instead of being sent to the system admin email.

But it does not stop there, it also seems like the "to name" is set to the new users id.

**Comment by marcodamm** [comment]
I can confirm this behavior and have some additional observations that align with the experiences of others.

The quoted comment from another user perfectly describes what I'm seeing:

> I Had the same bug, turns out that after a lot of playing around I noticed the notification gets sent to my notification mailbox instead of being sent to the system admin email.
> 
> But it does not stop there, it also seems like the "to name" is set to the new users id.

Specifically, I've found that the email notification for a new user signup is indeed not sent to the designated system administrator's email account. Instead, it's being directed to the email account configured to send out notifications.

While this might not be an issue for setups where the admin's email and the notification sender's email are the same, it creates a problem when they are distinct. In my scenario, the administrator's email is an employee's specific account, whereas the notification email is a general-purpose address. Differentiating between these two is crucial for proper administrative oversight.

This behavior, where the notification goes to the sending account rather than the intended recipient, effectively bypasses the system administrator, which can lead to delays in approving new users or even overlooked registrations.

**Comment by ignacionelson** [comment]
This issue is being closed as part of a bulk cleanup. ProjectSend has undergone significant changes since this was reported (including r1720 and r1994), and many older issues no longer apply to the current codebase.

If you are still experiencing this problem on the latest version, please open a new issue with updated details and we'll be happy to look into it. Thank you for your contribution!
